create database customer_behavior;
use customer_behavior;
SHOW TABLES;
SHOW COLUMNS FROM customer;
select*from customer limit 20;
-- what are the different revunes generated by male vs female costumers 
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- which costumer used discount and still spend more than avg amount
select customer_id,purchase_amount
from customer 
where discount_applied = 'YES' AND purchase_amount >=
(select avg(purchase_amount )
from customer);
--  top 5 prodcuts with highest review rating 
select item_purchased , avg(review_rating) as "avg product rating" 
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- avg purchase amount between all shipping
select shipping_type, avg(purchase_amount) as "avg purchase amount of shipping",COUNT(*) AS total_orders
FROM customer
group by shipping_type;
-- subscribers vs non subs 
select subscription_status , count(customer_id)as total_customer , Round(avg(purchase_amount),2),sum(purchase_amount) 
from customer 
group by subscription_status;
-- top 5 products with discount 
SELECT item_purchased,
       ROUND(100 * SUM(CASE 
                        WHEN discount_applied = 'Yes' THEN 1
                        ELSE 0
                       END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- NEW , RECURING , LOYAL CUSTOMERS BASED ON TOTAL NUMBER OF PREVIOUS PURCHASES SHOW THE COUNT OF EACH SEGMENT 
with customer_type as (
select customer_id , previous_purchases,
CASE
    when previous_purchases = 1 then "new"
    when previous_purchases between 2 and 10 then "recurring"
    ELSE 'loyal'
    end as customer_loyalty
    from customer )
    
    select customer_loyalty , count(*) as 'number of customers'
    from customer_type
    group by customer_loyalty ;

-- top 3 most purchased products within each category 
WITH ranked_products AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)

SELECT category,
       item_purchased,
       purchase_count
FROM ranked_products
WHERE rn <= 3;
-- Are Repeat Buyers (>5 Previous Purchases) Likely To Subscribe?
SELECT subscription_status,
       COUNT(*) AS repeat_buyers,
       ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;



